---

- name: Automate wordpress deployment using ansible & docker-compose
  hosts: web
  become: true
  tasks:

  - name: Install aptitude using apt
    apt: name=aptitude state=latest update_cache=yes force_apt_get=yes

  - name: Install required system packages
    apt: name={{ item }} state=latest update_cache=yes
    loop: [ 'apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common', 'python3-pip', 'virtualenv', 'python3-setuptools']

  - name: Add Docker GPG apt Key
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present

  - name: Add Docker Repository
    apt_repository:
      repo: deb https://download.docker.com/linux/ubuntu bionic stable
      state: present

  - name: Update apt and install docker-ce
    apt: update_cache=yes name=docker-ce state=latest

  - name: Install Docker Module for Python
    pip:
      name: 
        - docker
        - docker-compose

  - name: Create a directory compose
    file: path=/root/compose state=directory

  - name:  Copy docker-compose file into compose directoy
    copy: src=/root/ansible-lab/ansible-docker-wp/compose dest=/root/

  # Deploy our collection defined by the docker-compose.yml
  - name: Create & start services
    docker_compose:
        project_src: compose
    register: output
  
  - debug:
      var: output
