---

- name: Automate wordpress deployment using ansible & docker-compose
  hosts: localhost
  become: true
  tasks:

  - name: Install Docker on ansible node
    yum:
      name:
        - python3
        - docker

  - name: Install Docker on ansible node
    pip:
      name:
        - docker-compose

  - name: Create a directory compose
    file: path=/root/compose state=directory

  - name:  Copy docker-compose file into compose directoy
    copy: src=/root/ansible-docker-wp/compose dest=/root/compose

  # Deploy our collection defined by the docker-compose.yml
  - name: Create & start services
    docker_compose:
        project_src: compose
    register: output
  
  - debug:
      var: output
