---

- name: Automate wordpress deployment using ansible & docker-compose
  hosts: web
  become: true
  tasks:

  # Remove the existing services
      - name: Tear down existing services
        docker_compose:
           project_src: compose
           state: absent
      
     
