version: '3.7'

services: 
    db:
      image: mysql:5.7
      volumes: 
        - db_data:/var/lib/mysql
      restart: always
      environment: 
        MYSQL_ROOT_PASSWORD: root_password
        MYSQL_DATABASE: wordpress
        MYSQL_USER: user1
        MYSQL_PASSWORD: my_password

    web:
      depends_on: 
        - db
      image: wordpress:latest
      ports:
        - "9100:80"
      restart: always
      environment: 
        WORDPRESS_DB_HOST: db:3306
        WORDPRESS_DB_NAME: wordpress
        WORDPRESS_DB_USER: user1
        WORDPRESS_DB_PASSWORD: my_password

volumes: 
    db_data: {}    